title: Railly Clean
baseURL: /
params:
  header:
    type: header
    title: Railly Clean
    has_nav: true
    nav_links:
      - url: /
        style: link
        new_window: false
        no_follow: false
        type: action
        label: Home
      - type: action
        label: System
        url: /system
        style: link
      - type: action
        label: How it works
        url: /how-it-works
        style: link
      - type: action
        label: Evaluation
        url: /evaluation
        style: link
      - type: action
        label: Budget
        url: /budget
        style: link
      - type: action
        label: Team
        url: /team
        style: link
      - type: action
        label: Comments
        url: /comments
        style: link
    logo: /images/maroon-jupiter.png
    logo_alt: Railly Clean
  footer:
    type: footer
    has_nav: true
    nav_links:
      - type: action
        label: Contact Us
        url: /comments
        style: link
      - type: action
        label: Privacy and Terms
        url: /terms
        style: link
    has_social: false
    social_links:
      - type: action
        label: Twitter
        url: https://twitter.com/
        style: link
        new_window: true
      - type: action
        label: GitHub
        url: https://github.com/SDP-Team10
        style: link
        new_window: true
      - type: action
        label: LinkedIn
        url: https://www.linkedin.com/
        style: link
        new_window: true
    content: "&copy; Railly Clean. All rights reserved. 2021."
  domain: https://raillyclean.me
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
