title: Stackbit Starter Theme
baseURL: /
params:
  header:
    type: header
    title: Starter
    has_nav: true
    nav_links:
      - type: action
        label: System
        url: /system
        style: link
      - type: action
        label: How it works
        url: /how-it-works
        style: link
      - type: action
        label: Evaluation
        url: /evaluation
        style: link
      - type: action
        label: 
        url: /style-guide
        style: link
      - type: action
        label: Contact Us
        url: /contact
        style: primary
  footer:
    type: footer
    has_nav: true
    nav_links:
      - type: action
        label: Contact Us
        url: /contact
        style: link
      - type: action
        label: Privacy and Terms
        url: /terms
        style: link
    has_social: true
    social_links:
      - type: action
        label: Twitter
        url: 'https://twitter.com/'
        style: link
        new_window: true
      - type: action
        label: GitHub
        url: 'https://github.com/'
        style: link
        new_window: true
      - type: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: link
        new_window: true
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=starter&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
  domain: 'https://pink-mars-be984.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
